### ISSUE TITLE
Check validation of all inputs on another input change

### ISSUE THREAD

**Issue by luhovskyi** [chainlist/svelte-forms#10]
Is there a way to check validation of all form inputs whatever I change any of them?

### Steps to reproduce
1. Type some characters in the first input and make it invalid.
2. Focus second input and starts changing it - type first letter. First input on change of second input becomes valid.

### Expected behavior
1. Type some characters in the first input and make it invalid.
2. Focus second input and starts changing it - type first letter. First input on change of second input **stays invalid**.

**Comment by AnthyG** [comment]
This is a duplicate of #8
