### ISSUE TITLE
initCheck doesn't work in Sapper correctly

### ISSUE THREAD

**Issue by niklasgrewe** [chainlist/svelte-forms#15]
@chainlist Hi, thanks for this helper library to get validation done in Svelte.

I am using this library in Sapper. It works, but the form is valid although i have not entered anything. Only when I start to enter my email address the button becomes disabled. 

```html
<script>
  import { form, bindClass } from 'svelte-forms';

  let name = '';

  const myForm = form(() => ({
    name: { value: name, validators: ['required'] }
  }));
</script>

<style>
  :global(input.invalid) {
    border-color: red;
  }
</style>

<form>
  <input
    type="text"
    name="name"
    bind:value={name}
    use:bindClass={{ form: myForm }} />

  <button disabled="{!$myForm.valid}">Login</button>
</form>
```
Note: as soon as I load the page, the button is disabled briefly and then active again

It seems the initCheck function does not work properly
How can i solve this?

**Comment by chainlist** [comment]
Hi @niklasgrewe,

Gonna check this soon, I have another version that should be released soon and this version might fix your issue.

**Comment by chainlist** [comment]
With a little bit of delay, new version should fix your issue
