### ISSUE TITLE
How to make it validate field only after user input?

### ISSUE THREAD

**Issue by vedmant** [chainlist/svelte-forms#22]
Currently it shows error even on empty form, before user entered anything even with initCheck: false. How I can make it start validating field only after user typed something there? I still need validation during user input, but not before first input.

**Comment by DhyeyMoliya** [comment]
I also have the same issue. Setting `initCheck : false` does not make any difference.

**Comment by AnthyG** [comment]
Might be because `validateOnChange` gets called after the component gets initialized, I'll check this later or you can see if this is the case and report back.

**Comment by DhyeyMoliya** [comment]
I have added a pull request that fixes this issue. @AnthyG please check it out. It will be great help if you can release a new version as soon as you can. Because I want to use it in my project 🙏 .

**Comment by AnthyG** [comment]
Sorry, I forgot to add myself a reminder to check on this.  
@DhyeyMoliya, thanks for the PR!  
  
As I re-read the whole code I noticed that you could also just check if anything in the form is dirty and only then show the invalidated state. But I guess @DhyeyMoliya' implementation is better :D

**Comment by DhyeyMoliya** [comment]
Thanks @AnthyG , can you quickly move forward and create a new Release. So, I can update it in my project. I'm nearing a deadline 😄.

**Comment by AnthyG** [comment]
I can't create a release, because I'm not the Owner, only a Contributor (who rewrote some stuff to make it work better).  
However, I guess I can leave a good review on your PR and maybe @chainlist will accept it in no time :?

**Comment by AnthyG** [comment]
If you need this fix ASAP, then you could also just look into using your fork as a local npm dependency (at least I'm quite sure, that there is something like that).

**Comment by AnthyG** [comment]
This issue has been resolved with #23.

**Comment by chainlist** [comment]
As @AnthyG said, this issue has been resolved with #23.
