### ISSUE TITLE
Validation min not working correctly for strings

### ISSUE THREAD

**Issue by AugustHell** [chainlist/svelte-forms#24]
The validator for min is not working the expected way.
If used for a string it should be invalid, if the length of the string is lower then the requirement.
But typing in just a higher number into a type="text" field, holding a string var, makes the field valid.

Example:
```html

<script>
    let abc="";
    const theform = form(() => ({
       abc: { value: abc, validators: ["min:5"]},
    }));
</script>

<input type="text" name="abc" bind:value={abc} use:bindClass={{ form: theform }} />

{#if $theform.fields.abc != undefined && $theform.fields.abc.valid == false}
    <div>ABC should be at least 5 characters long</div>
{/if}

```

If I just type into the field the number 6, the field is valid and the error disappears.

**Comment by chainlist** [comment]
Hi @AugustHell,

If I understand correctly, you want to `min` validator to act like a `length` validator when the field is just a string?
