### ISSUE TITLE
"Function called outside component initialization" when "validateOnChange: true"

### ISSUE THREAD

**Issue by HimanshuSaikia** [chainlist/svelte-forms#28]
"Function called outside component initialization" when "validateOnChange: true" but works if "validateOnChange: false" .

But, "validateOnChange: false" is useless.

**Comment by stuible** [comment]
I have also been experiencing this issue ever since updating from svelete-forms 1.1.4 to 1.1.51.  I had to revert back in order to keep things working.  Loving this library so far and would be grateful if this could be fixed!

**Comment by DhyeyMoliya** [comment]
I have added a pull request https://github.com/chainlist/svelte-forms/pull/27 for solving this issue. @chainlist please re-consider it. I have given more explanation in there.

**Comment by stuible** [comment]
@DhyeyMoliya This appears to only be relevant to SvelteKit?  I am receiving this error using plain svelte + webpack.

**Comment by hsb-tonmoy** [comment]
The issue also occurs with Routify. Had to go with the SSR approach to solve it.

**Comment by jnishiyama** [comment]
> I have also been experiencing this issue ever since updating from svelete-forms 1.1.4 to 1.1.51. I had to revert back in order to keep things working. Loving this library so far and would be grateful if this could be fixed!

Same thing here, also getting this error using plain svelte. From a quick glance through the PR that was the version change, seems like it must have something to do with the bundling.

**Comment by chainlist** [comment]
Hi,

A v2 of svelte-forms has been released.
It was made using svelte-kit so it runs `svelte-forms` runs super smoothly with it, [documentation website](https://chainlist.github.io/svelte-forms/)!
