### ISSUE TITLE
Custom validator to check two fields match?

### ISSUE THREAD

**Issue by emiliedebra** [chainlist/svelte-forms#34]
I would like to add a validator that checks the values of two fields and ensures that they match, as you would when entering and confirming a new password, for example.

Is there a way to do this, or if not, is this a feature that could be added?

**Comment by chainlist** [comment]
Hi @emiliedebra,

Sorry for the late answer. You can still check out the v2 of `svelte-forms` that's just been released.
This feature is still not yet available but checking this could be done easier with a custom validator.

**Comment by chainlist** [comment]
@emiliedebra 

I just published a new validators that fulfill your need:

Check on the website the `matchField` validator.
