### ISSUE TITLE
Field-level `dirty` attribute

### ISSUE THREAD

**Issue by bry-an** [chainlist/svelte-forms#36]
I typically make extensive use of the dirty attribute when validating forms, e.g. a field cannot be invalid unless it is dirty. However this is hard to achieve with only a form-level dirty attribute. `dirty` does appear to exist on each field's validation object, but it references the form as a whole, so all field-level `dirty` attributes change together.

Am I missing this functionality somewhere? Or would others see this as a valuable addition to the library?

**Comment by chainlist** [comment]
Hi,

A v2 of svelte-forms has been released with the exact feature you requested.
Check out the new [documentation website](https://chainlist.github.io/svelte-forms/)
