### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by standup75** [chainlist/svelte-forms#4]
This seems interesting, but the examples are not working

**Comment by WaylonPohl** [comment]
@standup75 If you couldn't get the "Basic" example working try renaming '$loginForm' in the template to '$myForm' to match the const variable in the script. The "Advanced" example uses '$loginForm' so it might've been an oversight.

**Comment by sysmat** [comment]
`<button bind:disabled={!myForm.valid}>Login</button>`

`ValidationError: Can only bind to an identifier (e.g. `foo`) or a member expression (e.g. `foo.bar` or `foo[baz]`)`

**Comment by kamalkech** [comment]
@sysmat 

use : 
`<button disabled={!myForm.valid}>Login</button>`

instead of : 
`<button bind:disabled={!myForm.valid}>Login</button>`

**Comment by chainlist** [comment]
Hi, 

The readme has been updated and should work now.

**Comment by kamalkech** [comment]
@chainlist can u share your adress mail, j ai quelque chose a dire merci

**Comment by chainlist** [comment]
> @chainlist can u share your adress mail, j ai quelque chose a dire merci

Can't we just speak here? :)

**Comment by rawoke083** [comment]
Examples are broken again
`
value not declared
74:   <input type="text" bind:value={value} use:bindClass={{ form: myForm }}/>`

**Comment by chainlist** [comment]
I will fix this asap, thanks for reporting @rawoke083
