### ISSUE TITLE
Insufficient dirty/validate capabilities

### ISSUE THREAD

**Issue by jzillmann** [chainlist/svelte-forms#41]
## Here is what i want to do
- Render a form with a `submit` button
- The `submit` button is disabled unless the form (all fields) are valid
- Show errors under the inputs, but only if the fields have been touched (dirty)

## Here is where i'm running circles

- The initial form is `valid` & `dirty`
- Thus i call `form.validate()` to make the form invalid so the `submit` button is disabled
- But once i called `form.validate()`, all fields are flagged as dirty and the error messages are shown (which i only want once the field has been touched)

## Possible solutions

Once solution i could imagine is:
- I don't call `form.validate()`
- Disable `submit` if `!form.valid || anyField.isDirty`
- But then i need access to all the fields. Bundling them in an array before i pass them to `form()` failed due incorrect typescript types.

Also i don't understand why the initial form comes up as `valid` and `dirty`...!?

Any idea how i can achieve what i want ?

**Comment by chainlist** [comment]
Hi @jzillmann,

from what I understand setting the fields to dirty from a `form.validate()` is the cause of your troubles here.
And you are right to think that `form.validate()` or `field.validate()` shouldn't set the fields to dirty as well.

A fix about that is in progress!

Therefor just a `disabled={form.valid}` would be enough.

**Comment by jzillmann** [comment]
👍 Thanks! In the meantime I used a custom variation of the libraries code, but maybe I come back some time. I like the unobtrusiveness of the library a lot !
