### ISSUE TITLE
How to set value later

### ISSUE THREAD

**Issue by logineimer** [chainlist/svelte-forms#43]
How can I set a value imperatively for example in a reactive statement? This won't work because svelte-forms expects a Field<T> from me. I just want to set the value.

```
const name = field('name', undefined);
const _form = form(name);

$: name.set($someValueFromExternal); // Doesn't work
$: $name = $someValueFromExternal; // Doesn't work
```

**Comment by chainlist** [comment]
Hi,

Thanks  for your feedback. Indeed as of today this cannot be done. An improvement is in progress to make this case work.
Or at least to have a way to set a new value directly without being bother to pass a Field value.

**Comment by chainlist** [comment]
@logineimer A little update:

I came up with something that make both of your cases work like a charm. I still need to update the documentation and the tests and we are good to good for a new release pretty soon.

Keep an eye on the new version that is coming ;)

**Comment by logineimer** [comment]
Curious about it! Thanks!

**Comment by chainlist** [comment]
New version `2.0.7` is published and fulfil your needs.

Enjoy and thanks for the feedbacks.

**Comment by logineimer** [comment]
Thank you very much! I'll try it out after the holidays. Merry christmas, mate! :)
