### ISSUE TITLE
Form and Field Validity - checkOnInit 

### ISSUE THREAD

**Issue by alexstaroselsky** [chainlist/svelte-forms#45]
`checkOnInit` does not seem to marking a `form` or a `field` in the `form` as invalid on initial render when `checkOnInit` is true.

https://svelte.dev/repl/1d6d64e61cfe4f1788fe3627bb27a690?version=3.44.3

Also notice that if `validateOnChange` is not set in options when `checkOnInit` is set to `true`, it does not seem to re-validate  the`field`. As in, in a dirty state, if a text field with `required` is set back to falsy, `field` is not marked as invalid. May be expected behavior as I don't see `validateOnChange` or similar options being defaulted in `createFieldStore`.

https://svelte.dev/repl/f6915e493d574d3c91ac9759701f650e?version=3.44.3

**Comment by alexstaroselsky** [comment]
Did you intend to have `options` to `createFieldStore` to have a default object with `validateOnChange` property defualting to `true`?

**Comment by chainlist** [comment]
Hi @alexstaroselsky,

The bug has been fixed with the new version 2.0.8. You might want to update your package project if you didn't solve it with a workaround.

FYI: The issue was due to a initialization error of the default options objects.
