### ISSUE TITLE
Possibility to retrieve the complete form state programatically

### ISSUE THREAD

**Issue by seriousManual** [chainlist/svelte-forms#49]
When submitting a form, it is neccessary to access the data that has been entered in any field.
If I get this correctly, currently it is neccessary to access each field individually to construct a form state.

It would be nice to have a way of accessing the complete state at once.
Maybe something like:

```
<script>
    const firstName = field('firstName', '', [required()], { checkOnInit: true });
    const lastName = field('lastName', '', [required()], { checkOnInit: true });
    
    const myForm = form(firstName, lastName)

    function onSubmit() {
       console.log('form has been submitted, current state: ', $myForm.state())
    }
</script>

  <input type="text" bind:value={$firstName.value} />
  [...]
  <button on:click={onSubmit}>submit</button>
```

Let me know if this sounds something you'd be interested in, I'd like to try my luck on a PR!

**Comment by seriousManual** [comment]
I played around with the codebase for a bit and did a PR already
https://github.com/chainlist/svelte-forms/pull/54

**Comment by chainlist** [comment]
Hi @seriousManual,

Thanks for your feedback, I'm reviewing yours as soon as I can (I'm currently in HM).
But at first glance, everything seems to be pretty nice and this should be followed with a new version soon!
