### ISSUE TITLE
How to get all values (object/array) ?

### ISSUE THREAD

**Issue by rawoke083** [chainlist/svelte-forms#53]
Hi  how do we access all the values at once to submit the values ?

i.e:

`myForm.values() ?`

**Comment by seriousManual** [comment]
currently that's not possible, I already posted an issue (https://github.com/chainlist/svelte-forms/issues/49) about the same issue

**Comment by chainlist** [comment]
hi @rawoke083,

Indeed @seriousManual made a MR about that specific case. I'm going to review it pretty soon and you'll be notified when a new version is released.

If you don't mind, I'm closing this issue as duplicate of #49.
