### ISSUE TITLE
Published package contains *a lot* unneccessary stuff

### ISSUE THREAD

**Issue by seriousManual** [chainlist/svelte-forms#57]
I was just installing the latest version of svelte-forms (thanks for the PR merge!) and incidentally realized that alongside svelte-forms a number of other (unrelated) dependencies got installed, like

* lodash.kebabcase
* prism-svelte
* prismjs
* svelte-awesome
* ua-parser-js

A couple of them are even nowhere used.

And after inspecting the installed package I saw that there is *a lot* of stuff in there that is not actually related with the library at all.
Here are two screenshots of all the installed files, as I see it only the green marked files are *actually* neccessary for someone consuming this library...

![image](https://user-images.githubusercontent.com/1330022/151518358-f3adfe8c-e5fb-43cf-9b63-3ad35468f89c.png)
![image](https://user-images.githubusercontent.com/1330022/151518114-f72413c0-45a1-42fe-b961-0809bcb315fc.png)

I would not be surprised if the issues described in #48, #55 and #58 are somehow related to the abundance of configuration files and superfluous resources.

**Comment by seriousManual** [comment]
I switched to the previous version (`2.1.0`) and that's what its content looks like now:
![image](https://user-images.githubusercontent.com/1330022/151536024-75b051f5-32e7-4540-b634-1d0b5aa5eacd.png)


Is it possible that you accidentally deployed the whole repository to npm instead of using the script from the package.json?
![image](https://user-images.githubusercontent.com/1330022/151536130-4508e56c-f8b4-45eb-ab65-f3745e73d6a8.png)

**Comment by chainlist** [comment]
Good catch!

This is a bad habbit I have from using `yarn`.

With `yarn` you can use the following `yarn package` whereas with npm you need to do `npm run package`.

There is a script called `publish` and I ran `pnpm publish` instead of `pnpm run publish` which indeed published the whole repository instead of just the package repository.

Fixing and invalidating this version right now.

Sorry for the inconvenience. I'm going to rename the script name to not have this issue anymore

**Comment by chainlist** [comment]
New package has been published under version `2.2.1`.

To prevent this from happening:
- Rename `deploy` script to `deploy:docs`
- Rename `publish` script to `deploy:package`
- Added a new script `deploy` which is doing `deploy:docs && deploy:package`

Thanks for noticing that very quickly. Doing stuff when on vacation is never good! Learned that the hard way.

**Comment by chainlist** [comment]
![image](https://user-images.githubusercontent.com/1869318/151633032-cefc8c80-d82a-4e30-a46f-33236ae00734.png)

**Comment by seriousManual** [comment]
Thanks for the fix!

I'm not very familiar with pnpm, but I know that for npm certain life cycle hooks exist that can be leveraged to do any preparations that are neccessary before actually publishing.
Than simply running "publish" would work as intended.
