### ISSUE TITLE
Failed to resolve entry for package "svelte-forms"

### ISSUE THREAD

**Issue by Snukii** [chainlist/svelte-forms#58]
I'm running into this problem trying to use svelte-forms in a sveltekit project:

`Failed to resolve entry for package "svelte-forms". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "svelte-forms". The package may have incorrect main/module/exports specified in its package.json.`

I've simply `yarn add`ed svelte-forms and put `import { form } from 'svelte-forms';` in a component.

I'm just running using `yarn run dev`

My project also has typescript.

**Comment by chainlist** [comment]
Hi,

Thanks for your comment, this issues is going to be fixed in the next version `2.2.1` sorry for the annoying bug.
