### ISSUE TITLE
[REQUEST] summary() should be added to form store

### ISSUE THREAD

**Issue by eden-omb** [chainlist/svelte-forms#59]
Right now `summary()` works great, but you can't subscribe to it.

**Comment by chainlist** [comment]
Hi @eden-omb,

Thanks for the suggestion.
Can you provide a use-case of the request you are asking for?

Today, the main way to detect changes is through the fields directly.

`summary` returns a plain object every time it's called. Giving the ability to subscribe to it would require us to save an additional derivedStore. And I don't see any benefits with this method.

@seriousManual implemented that method for it to be called programmatically and be able to retrieve all the data in one-go.

**Comment by eden-omb** [comment]
My use case is populating an `<output>` with intermediate values from a form. Sure, I can pass the individual values, but it's much more convenient to work with the summary and have it update each time the form updates. Right now I'm using this with an expression `$form && form.summary()` so Svelte reevaluates it every time the `$form` store updates, but it would be nicer to simply do `$form.summary()`. I don't know that a new derived store would really be necessary.

**Comment by chainlist** [comment]
Watch expression is the perfect solution to you use case also (let's call that a workaround).

```javascript
$: summary = $form && form.summary();

<output bind:value={summary} />
```

**Comment by eden-omb** [comment]
This is precisely what I'm using now as a workaround :)
What I'm suggesting is not to put a store in a store. This `$form && form.summary()` workaround only works because `$form` gets updated appropriately for `summary()`. Why not just add the full summary to what's in the `$form` store, next to `valid`, `dirty`, and `errors`? Then you can do `$form.summary` just like you do `$form.errors`? I can get around sometime this week to make a PR if that sounds good to you.

**Comment by seriousManual** [comment]
Though I'm not in favour to adding another method to the store's value (`$form`) itselves, @eden-omb 's point is a valid one:

There are methods on the form store and there are methods / properties on the store's value. The only difference to a certain point is the use case: programatically or as a subscription inside a template.
As an example: `hasError` sits on the store's value so it is going to be used inside a template. But at the same time in certain use-cases it would also be helpful to have this on the form itselves. 

I'm not sure where to draw the line here and if maybe there already have been some thoughts put into this, but it might make sense to explore this a bit further?

**Comment by chainlist** [comment]
Hi @eden-omb,

I see what you mean! Indeed my idea was a bit close minded on that "store in a store". 
Computing another property on the form itself could work!

The thing that I'm wondering now is: Should we keep the name `summary` for that property?

Wouldn't it be too confusing with that method `summary()`? It would also makes sense.

`myForm.summary()` for programmatic call.

and `$myForm.summary` for any update to the store.

Could work

**Comment by chainlist** [comment]
@eden-omb I created a PR for you to check if it matches your request.

@seriousManual I had to change your `summary` method to avoid duplicates and it's now returning the summary property after a `get()` on itself instead on every fields.

It acts as a shorthand to `summary` property but I don't want to remove it since people might have started to use it

**Comment by eden-omb** [comment]
Looks great! There could be handy use cases for the summary method `form.summary()` to go with something like `form.reset()`, many people would only want to read it on submit anyway. Seems reasonable to have both. In any case this issue can be closed as soon as that handsome PR is merged.

**Comment by seriousManual** [comment]
Looks nice, the only thing I'd like to bring up:
On every form change the summary is recalculated inside the derived store, even if it is not used anywhere. Maybe the calculation could be done lazyly, e.g. via a getter?

**Comment by chainlist** [comment]
@seriousManual good optimisation here.

I tried that, it's working and also implemented that for `errors`.

**Comment by seriousManual** [comment]
nice!
