### ISSUE TITLE
How to make it work on button click?

### ISSUE THREAD

**Issue by rykiplov** [chainlist/svelte-forms#6]
It looks nice, but how to make it work on button click?
I tried this:

`use:bindClass={{ form: checkoutForm, name: 'shipping_lastname', valid: 'validation-passed', invalid: 'validation-failed'}}`

But validation starts instantly when user starts to enter input value. Also, this code adds invalid class to other empty inputs in the form. Can someone help please and tell me how can i make same behaviour, but only after button click? Thanks

**Comment by chainlist** [comment]
Hi rykiplov,

Sorry for the late response I took some days off recently.
I will look at your issue as soon as I can.

**Comment by rykiplov** [comment]
Thanks, we want to use you validation on production app, we just need to make it work after button click

**Comment by chainlist** [comment]
Hi,

Can you share the code that is not working so I might have a look to your use case?
I understand you might be under NDA so try to recreate the piece of code.

Thanks

**Comment by rykiplov** [comment]
Yeah, I recreated my case, [here's](https://github.com/rykiplov/svelte-forms-example) it. I have Magento checkout page with 2 steps (shipping and billing) made with Svelte. Here's questions that I can't resolve by myself.

1. How to make validation starts working only after 'Next step' button click? When users just came on page and haven't entered anything in input fields he shouldn't see validation error message.

2. How to change form object to change fields to be validated? For example, if you open my app, enter Firstname and Email fields (but not Lastname), then you click 'Hide lastname' button. The field and error message will be removed from DOM, but it still says that form is invalid. I would like to make following - when field is removed from DOM its not going to be validated anymore.

**Comment by chainlist** [comment]
Hello rykiplov,

I updated the package to 1.2.0.

For your problem #1:
I pushed a new form configuration field named `initCheck` to avoid validating the form at initialization, and you have now an handy funtion on your `myForm` called `validated` to perform the validation on call.

For you problem #2:
I pushed a new validator configuration named `enabled` to tell the form to perform a check or not on that field. You should now bind your email validator to a local boolean variable, and on your hide button, set this variable to false to avoid checking the email field.

**Comment by rykiplov** [comment]
Hello chainlist, thank you for help, I just tried first fix and there's an errors, can you please take a look at [here](https://svelte.dev/repl/da05ebc70ca14908b0684f76062a15cd?version=3.15.0)? Even if you delete error messages, .validate() method does nothing, when you click on button form is still valid even with empty fields.
