### ISSUE TITLE
[BUG] Combined example in docs

### ISSUE THREAD

**Issue by Snukii** [chainlist/svelte-forms#62]
I think I spotted an error in the example for combined.

It has
`const myForm = form(name);` which I believe should be `const myForm = form(fullname);`
And the same thing for the button in the example, it has:
`on:click={name.validate}` which I believe should be `on:click={fullname.validate}`

**Comment by chainlist** [comment]
Hi @Snukii,

Thanks for your suggestion, it's going to be fixed soon.
