### ISSUE TITLE
[REQUEST] Add `clear()` in addition to `reset()` for fields and forms

### ISSUE THREAD

**Issue by eden-omb** [chainlist/svelte-forms#63]
**Is your feature request related to a problem? Please describe.**
Right now, when you `reset()` fields which have an initial value, they get reset to that initial value, which makes sense. But if I want to load in initial values as safe defaults but have them conveniently cleared away this is currently impossible except by setting the values programmatically when the form loads.

**Describe the solution you'd like**
I'd like to have `field.clear()` and `form.clear()` which set the field or form to an empty value, rather than the initial value.

**Describe alternatives you've considered**
Setting the values when I first load the inputs and use `.reset()` instead.

**Comment by chainlist** [comment]
Hi @eden-omb,

Good suggestion indeed, I found myself in a similar case as well.
But, my question is: What's an empty value?

Would it be better to consider empty as `undefined` ?

Or something like:
* If the field is a number, empty is actually 0
* If the field is a string, empty would be `''` (an empty string)
* If the field is an object, should we set the object to `{}` or `undefined` or every field to their respective empty value (see above for ex)?

My best guess and the least opinionated solution would be to set everything to `undefined`.

**Comment by eden-omb** [comment]
Don't fields already have an empty value? I've been setting mine as `null` and it's been working out well so far. Semantically `null` seems the better choice to me as a managed value being intentionally marked as empty, but it's moot point here or there between that and `undefined`. It's worth noting that all `<input>`s seem to have an empty value of `''` regardless of type.

Checkboxes are bound to a group and therefore have to have an empty value of an empty array or else Svelte breaks when you put it in `bind:group`. When can a value be an object?

**Comment by chainlist** [comment]
For base HTML inputs / select there is no object.

But we have to keep in mind that could be use with custom form element from others libraries that might require object as value.

`null` would be fine by me as cleared value

**Comment by eden-omb** [comment]
`null` sounds good as cleared and default initial value. Object values could also be nice for like nested composite values maybe, but that's a question for further down the line.

I'll try getting around this week to sending a PR if you don't beat me to it. The only thing I didn't manage to solve from outside yet is clearing the validation like `reset()` does, or setting fields to `null` without triggering validation, but I'm sure it wouldn't be too complicated to solve from the inside.
