### ISSUE TITLE
[BUG] Invalid field marked as valid when validateOnChange is false (CRITICAL)

### ISSUE THREAD

**Issue by omer-g** [chainlist/svelte-forms#76]
**Describe the bug**
When `validateOnChange` is `false` then when the field store changes, `processField` is called with `[]` as `validations`. This causes `valid` in line 49 of `createFieldStore.js` to be trivially `true`, and the field is seen as *valid* until manual validation (even when it's value is *invalid*).

**To Reproduce**
1. Create field with `validateOnChange` as `false`,  and some validator
2. Create text box and bind the field to it
3. Enter value that the validator would not see as valid
4. Check `valid` in field

**Expected behavior**
`valid` should remain `false` until the value is validated

**Additional context**
The issue resolves by changing the `if` in `createFieldStore.js` line 47 to be:
`if (validations && validations.length > 0)` 

But I think it might be cleaner to pass a `null` or some other value instead of `[]` in line 75, to make it explicit that no validation should occur and to distinguish between the case where the validators array is purposefully empty.

Currently the call is:
`_set(processField(field, [], { dirty: true }));`

Could be:
`_set(processField(field, null, { dirty: true }));`

**Comment by omer-g** [comment]
Hey @chainlist ,
I cloned the repo, fixed the issue and wrote a test for it. Would be happy to make a PR, but would appreciate if you could answer a few technical questions:
1. I did `npm install` and it added `package-lock.json`. Should this file be committed in the PR, or should I add it to `.gitignore`? (or something else?)
2. How to treat versioning? Should I just manually change version in `package.json` and `CHANGELOG` to `2.3.1`?

**Comment by chainlist** [comment]
Hi!

Sure thing, thank for the PR!

For you question: 

1. For now, I'm manually changing the version number, I need to automatize everything. But very taken with this end of quarter.
2. package-lock.json should not be committed though as I personally prefer to use `pnpm` instead of `npm`.
