### ISSUE TITLE
bug: making one input invalid, then making another valid makes the whole form incorrectly valid

### ISSUE THREAD

**Issue by wbhob** [chainlist/svelte-forms#8]
Steps to Reproduce: make 2 inputs. make both required. make the first valid, then make it invalid. then make the second valid. the whole form will show as valid.

Expected Behavior: the whole form should be invalid. I think this is likely because it's only checking changed inputs, but not persisting the previous invalid states. There should be an option to re-check every input every time, or make this the default.

**Comment by wbhob** [comment]
It doesn't seem like any of the code in the README works, either, which makes it tough to know if I'm doing this right or not.

**Comment by uzarsalan** [comment]
same issue

**Comment by AnthyG** [comment]
I have somewhat fixed this although I now have to fix / reimplement the `form.dirty` and `field.enabled` stuff.  
I'll make a PR later today.
