### ISSUE TITLE
[REQUEST] optional validator

### ISSUE THREAD

**Issue by andrejohansson** [chainlist/svelte-forms#91]
**Is your feature request related to a problem? Please describe.**
I would like to validate a field as **optional** but if it exist, it should be valid according to a list of other validators.

**Describe the solution you'd like**
Something like

```
const email = field('email', guest.email, [optional([emailValidator()])], options);
```

**Describe alternatives you've considered**
A custom attempt

```ts
export function optional(validation: Validator) {
		return async (value: any) => {
			const validator = validation(value);
			const hasValue = !(value === undefined || value === null || value === '');

			if (isPromise(validator)) {
				const result = await validator;
				return { valid: result.valid || !hasValue, name: result.name };
			}

			return { valid: validator.valid || !hasValue, name: validator.name };
		};
	}

const email = field('email', guest.email, [optional(emailValidator())], options);
```

**Comment by pepegc** [comment]
salut @chainlist, I need this too. Looking at `createFieldStore.ts` and seeing how validators are handled, I think it would be better to add a `isOptional` boolean to `FieldOptions`. Then `getErrors()` can take an additional attribute `isOptional` and then after `const v = getValue(value);` we could add a
```
if (isOptional && !v){
  return []
}
```

**Comment by chainlist** [comment]
merged
